# H2
server:
  port: 9000
spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:db
    #url = jdbc:h2:file:C:/data/sample
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
