# Oracle
server:
  port: 9004
spring:
  profiles: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/orcl
    username: scott
    password: scott
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate.use-new-id-generator-mappings: false
    hibernate.ddl-auto: update
