# SqlServer version
server:
  port: 9002
spring:
  profiles: mssql
  datasource:
    url: jdbc:sqlserver://localhost:1434;database=db;TrustServerCertificate=True;
    username: sa
    password: Root001!
    platform: mssql
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
